### ISSUE TITLE
Static site generator HTML output is minified

### ISSUE THREAD

**Issue by kamsar** [connectivedx/fuzzy-chainsaw#101]
## Expected Behavior
The output from the HTML generation should be pretty-printed since that markup will be for public consumption by backend devs integrating to the platform of choice.

## Current Behavior
The markup is minified:
![image](https://cloud.githubusercontent.com/assets/103677/20143471/f337e4fa-a64d-11e6-938c-ff7ba05b5b7d.png)

## Possible Solution
I did not see any obvious pretty flags on the static site generator plugin being used.

## Context
Minified HTML will make it awfully hard to consume the rendered templates, and as JSX is not remotely HTML-like, consuming the templates directly is no longer an option. Especially as integrations change, wrappers are altered, etc this will be a dealbreaker.

**Comment by krambuhl** [comment]
We are using an xml formatter on the style guide to fix that..  I had imagined that integration would be mostly happening through the styleguides HTML tab, as the style guide becomes the source of truth. I wonder if putting the pages into the style guide would solve the issue of needing to see full pages?

**Comment by krambuhl** [comment]
note to me: This should be implemented in the render function of the static site generator

**Comment by pgregorova** [comment]
@kamsar @krambuhl I was actually liking the minified output. :) For as long it gets done during production build, I would be ok with not having it in watch .

**Comment by kamsar** [comment]
We wouldn't want minned HTML from a prod build because that's not the output that will be served from whatever backend FC is used on - unless you're developing a static HTML site! Someone will always need to consume it, and in cases where the markup may split across several components there's a definite need to get human readable larger markup chunks. Minned HTML also has very diminishing returns as long as you're gzipping the page - like 1-3% reduction on a ~20k markup page. Which is why we aren't usually doing it.

Though the formatted HTML in the styleguide is a good start, and I didn't realize it was there when opening this ticket.

**Comment by krambuhl** [comment]
I think we are going to do some post processing on the html for relative paths, this would be a good place to make this change as well. I'll plan on doing this on my current open branch around static rendering.
