### ISSUE TITLE
CSS variables are not part of watch

### ISSUE THREAD

**Issue by drolsen** [connectivedx/fuzzy-chainsaw#106]
When editing or adding variables or variable files, watch is not picking up on changes and requires a non /variables/* edit to see changes made in variables.

**Comment by krambuhl** [comment]
it looks like this is related to postcss-import.  webpack pack is not being introspective about @import inside of postcss, I think one of the changes in #108 will make it so we can just do all the postcss transforms at the end, instead of in a loader and not muck around with postcss-import

**Comment by drolsen** [comment]
Looks like this issue still remains for me today unfortunately.
