### ISSUE TITLE
Dear Mixins, we need to talk..

### ISSUE THREAD

**Issue by drolsen** [connectivedx/fuzzy-chainsaw#111]
![Image of Yaktocat](https://media.giphy.com/media/l0HlJXnCB4zomuLte/giphy.gif)

Forgive me if this conversation has already happen. We don't have a need for any of our old mixins to be moved over thanks to autoprefix and simple depreciation correct? I just wanted to go over each one to make sure we are all on the same page here, and also had a question down below.

- **aspect-ratio**
Depreciated: there is a plugin for this. Should this be part of baseline?
https://www.npmjs.com/package/postcss-aspect-ratio
- **font-size**
Depreciated: nextcss takes care of px fallbacks for us when using em or rem units
- **gradients**
Gradient vendor rules are never going to die. But there are questions I have like, how often do we use these, is there a plugin for this, and WHY DOES EVERYONE HATE RADIAL? ;)
- **high-dpi**
What do we do about this one?
- **icon**
Depreciated: already moved into a tag correct, mixin not needed?
- **media**
Depreciated: nextcss allows for custom media queries, and syntax is shorter.
- **placeholder-color**
Unused: I made this, and used it I think maybe once.
- **retina-image**
Depreciated: postcss plugin for this now. Should to be part of baseline? 
https://www.npmjs.com/package/postcss-retina-bg-img
- **rgb-background-color**
Depreciated: nextcss has a TON of color features already 
- **transition** 
...why did we have this one again?

### My question
Knowing we won't have any actual mixins for baseline, do we still want to allow people to author them? It's one thing to not provide mixins (trust me I'm all for it, look how clean it is), but its a whole other thing to not allow mixins to be crafted out of the box. I'm kinda leaning on the side of yes to allow it right now. Thoughts? 

There are a ton of different mixin flavors out there for postcss it looks like:

- https://www.npmjs.com/package/postcss-mixins
- https://www.npmjs.com/package/postcss-mixin-from
Does what it says, but I'm not a fan of the syntax for both creating and using.
- https://www.npmjs.com/package/postcss-simple-mixin
Does what it says, but even less of a fan of the syntax issues I didn't like out of the first one.
- https://www.npmjs.com/package/postcss-sassy-mixins
Oh mama, simple syntax we all already know how to use, easy to read and does what its suppose to. However, I'm very bias as I've been using sass for too long.

Discuss!

**Comment by krambuhl** [comment]
@drolsen @pgregorova @elseloop @stoff since y'all have had some time to build using postcss, what is the feeling on this issue at this point?  Last we talked, we were going to see if there were any clear gaps that still need to be filled.

**Comment by krambuhl** [comment]
Going to close this issue for now.  Please reopen/comment if you end up finding reasons to use Mixins.  It seems that most of our use cases have been covered by custom property sets.
