### ISSUE TITLE
Reference image assets in CSS?

### ISSUE THREAD

**Issue by drolsen** [connectivedx/fuzzy-chainsaw#113]
~~How do we reference image assets when images are being cache poped under unique numbers out in dist?~~

Windows machines, while saving a new image to a component or tags assets folder, build watch sometimes crashes, or nothing happens at all and must stop watch an run build manually.

**Comment by krambuhl** [comment]
Images can be pulled into code via `url(./file.png)` in css.  This behaves in the same way that require('./local-module.js') does.

```
.box {
  background-image: url('./assets/image.png');
}
```

When you require an image like that, webpack will grab that image, put it in the dist assets folder, and return the path to than eventual asset with it's hash applied.

The file structure we have used is:

```
- tags/Box
- tags/Box/assets/**images**
- tags/Box/Box.css
```

**Comment by krambuhl** [comment]
@drolsen can you provide steps to reproduce the image crash? It'll give me a better idea of how to debug

**Comment by drolsen** [comment]
Ah ha! Ok, so turns out this is not related to images kinda.
With build watch running, copy over an image (not save a new image) from another folder to a component or tag's local asset folder. Notice that on Windows, the build watch does not react to the manully copied over files. 

Stop build watch (ctrl-c) and try to run a build, and you get the following error:
![image](https://cloud.githubusercontent.com/assets/553928/20401580/40cecfba-acae-11e6-9634-2490d5254549.png)

Try going into the dist folder and you get via explorer:
![image](https://cloud.githubusercontent.com/assets/553928/20401635/75e2df84-acae-11e6-89f5-79d21da2adeb.png)

Now here is the kicker... the only way to get build to work again and dist to be accessible again is to close sublime editor..

Had the images you move over by hand picked up watch change, might of not ever found this so that's why I say its semi-related but the dist folder halt is the actual issue.

**Comment by krambuhl** [comment]
After this situation, are you able to do `npm run build` with success?  Or does it require that you exit sublime and delete dist manually?

**Comment by drolsen** [comment]
I've not experienced this issue as of late so must be fixed now.
