### ISSUE TITLE
Pages not showing up in index.

### ISSUE THREAD

**Issue by drolsen** [connectivedx/fuzzy-chainsaw#116]
I've tried to make a new page under /pages/test.jsx and I'm able to reach it via /test.html but it is not being listed out on /index.html under the pages category.

**Comment by krambuhl** [comment]
this is a known bug with static site generator, I published a fork (https://www.npmjs.com/package/static-generator-webpack-plugin) and need to implement

**Comment by krambuhl** [comment]
@drolsen I think I misunderstood this issue. Are you expecting that pages be indexed automatically like tags and components?  currently you need to manually add pages to the index in `source/pages/index.jsx`

**Comment by drolsen** [comment]
Correct, I was expecting pages to be indexed. I wouldn't mind a new commend for making pages either if that is what is needed to make them indexed win win imo.

**Comment by krambuhl** [comment]
okay, this is added in the static renderer PR.  By default page indexing will be turned on, but on a new project it would be easy to remove.

**Comment by krambuhl** [comment]
PR has been updates with better indexing tools.
