### ISSUE TITLE
Component / Tag Default Syntax

### ISSUE THREAD

**Issue by drolsen** [connectivedx/fuzzy-chainsaw#117]
I noticed that when generating either tag or components the .jsx file produces:

```
<div className={"XXXX " + className}>
	{children}
</div>
```
but shouldn't we recommend:
```
<div className={`XXXX  ${className}`}>
	{children}
</div>
```
so noobs like me wont keep forgetting this method, and stop falling for nasty concatenation?

**Comment by krambuhl** [comment]
good catch, I'll put this in my next bucket of fixes

**Comment by krambuhl** [comment]
This already got fixed in that last general improvements PR.
