### ISSUE TITLE
Adding webfonts to a project

### ISSUE THREAD

**Issue by pgregorova** [connectivedx/fuzzy-chainsaw#123]
Working on a project where I need to host fonts. I tried to manually adding them to variables or even tag folder, but they don't seem to be compiled into dist assets folder like images tend to do. 

Wondering whether this has been already addressed or implemented yet.

**Comment by krambuhl** [comment]
No, somehow we totally forgot about fonts!  I was going to make a pass at built in tags today, I'll make sure to add a <FontFace /> type component

**Comment by pgregorova** [comment]
@krambuhl Cool, I just wanted to make sure I wasn't missing something as I am trying to still familiarize myself with everything. Like, even being able to add a separate js file. Not sure where to put, so it would get compiled into dist folder as well. :)

**Comment by krambuhl** [comment]
this is merged, check out `/source/variables/fonts.css` for and example.
