### ISSUE TITLE
Adding favicons

### ISSUE THREAD

**Issue by pgregorova** [connectivedx/fuzzy-chainsaw#124]
Not sure if anyone has worked on this yet but I was looking into adding favicons to my project where I would account for all devices (iOS, Android, Windows,...) but that requires more than just adding few .png files. 

For instance, some are served via `manifest.json` file and Windows 8 and 10 require `browserconfig.xml` file. 

As an example, you can see [an audit](http://realfavicongenerator.net/favicon_checker?protocol=http&site=www.connectivedx.com#.WDLv5rIrJhF) of our CDX site. :) 

Whenever I tried to add those files, my build would fail, not to mention, i wasn't sure where to add those files, so they would successfully get compiled. Maybe they could be in root of the project? Where would I add all the images? Would we have those in root or would we have a designated folder for them, maybe even with the .json and xml file there as well?

The final output would look something like this:
`<link rel="apple-touch-icon" sizes="180x180" href="/dist/assets/images/content/apple-touch-icon.png">`
`<link rel="icon" type="image/png" href="/dist/assets/images/content/favicon-32x32.png" sizes="32x32">`
`<link rel="icon" type="image/png" href="/dist/assets/images/content/favicon-16x16.png" sizes="16x16">`
`<link rel="manifest" href="/dist/assets/images/content/manifest.json">`
`<link rel="mask-icon" href="/dist/assets/images/content/safari-pinned-tab.svg" color="#71a232">`
`<link rel="shortcut icon" href="/dist/assets/images/content/favicon.ico">`
`<meta name="msapplication-config" content="/dist/assets/images/content/browserconfig.xml">`
`<meta name="theme-color" content="#ffffff">`

A new favicon set can be easily generated, including custom settings, using an online free[ favicon generator](http://realfavicongenerator.net/).

**Comment by kamsar** [comment]
I'd love to see some metrics on how often all these advanced integrations are actually used (c'mon who actually pins a site to the start menu on Windows 8/10?). FWIW, favicons - at least in terms of Sitecore sites - become the domain of the CMS after the HTML is integrated. That includes all the output tags.

**Comment by pgregorova** [comment]
@kamsar This was generated for the most current devices, browsers, I left the legacy stuff out, I am sure we can scale things down but figured this was a good place to ask how to reference other file extensions if wanting to add them, their location and paths to resources, etc. 

And, I am actually one of those people who likes to bookmark sites I visit often, whether on my device or computer. :p

**Comment by krambuhl** [comment]
This will do what we need: https://github.com/jantimon/favicons-webpack-plugin

**Comment by krambuhl** [comment]
FavIcons are now generated automatically on the `2.0` branch using the `source/favicon.png` source asset.
