### ISSUE TITLE
Self-closing <meta> in <head>

### ISSUE THREAD

**Issue by pgregorova** [connectivedx/fuzzy-chainsaw#127]
I've noticed that `<meta charset="utf-8" />` after page compiles, gets shortened to `<meta/>`.

Tried to look into what's causing it but kept running into a wall. :(

**Comment by krambuhl** [comment]
It looks like this is related to camelcasing in react.  I have to admit this is an odd one to me, but `chatset` is not a valid property, you need to use camelCase like `<meta charSet="utf-8" />`

https://github.com/facebookarchive/react-page/issues/41
