### ISSUE TITLE
pathing to tap-min

### ISSUE THREAD

**Issue by stoff** [connectivedx/fuzzy-chainsaw#128]
when running build from a different root location, the path to tap-min does not resolve properly.  we came across this when integrating with Legendary Pancake, where the build stack is down a long path and the output path is not a child of the FC build root.

resolution was to apply an absolute path in webpack.factory.js:
```
  const componentTests = testsConfig(baseOutput({
    entry: dirs.source + 'tests.jsx',
    outputScript: '/tmp/tests.js',
    reporter: __dirname + '\\node_modules\\.bin\\tap-min'
  }));
```

This is a Windows-specific fix and logic should be added to switch the path delimiter per platform.

**Comment by krambuhl** [comment]
https://github.com/substack/node-resolve

**Comment by krambuhl** [comment]
basically, https://www.npmjs.com/package/tap-webpack-plugin is resolving the reporter module from `process.cwd()` instead of the file `__dirname`, so it's looking for `tap-min` in the LP node_modules when run via `lp watch` instead of the project node_modules directory.
