### ISSUE TITLE
In need of "srcset"

### ISSUE THREAD

**Issue by pgregorova** [connectivedx/fuzzy-chainsaw#130]
I've been trying to use srcset for images but somehow it keeps getting ignored during build, no matter what I try. Not sure if I am just doing it wrong or there needs to be support added for it. 

It seems to be that just `srcset` attribute is being ignored, anything else I've added, like `sizes` (following [RICG syntax](http://responsiveimages.org/)) works just fine.

**Comment by krambuhl** [comment]
Looks like the same issue as #127.  try using `srcSet` instead of `srcset`.  Close if this works for you.

http://stackoverflow.com/questions/34695899/why-is-react-js-removing-the-srcset-tag-on-img
