### ISSUE TITLE
Provide options for styleguide examples

### ISSUE THREAD

**Issue by krambuhl** [connectivedx/fuzzy-chainsaw#136]
There is currently no options to configure the styleguide example output. If you want something like a dark background for your example, you have to hack away.  We should add an options field to component test files that the styleguide `Example.jsx` can make use of.

```jsx
{
  name: "component test",
  options: {
    darkBackground: true
  },
  component: <div />,
  test(t, component) { ... }
}
```

This allows us to style the example component container as well as just the component.

**Comment by elseloop** [comment]
Having an option to exclude tests from the styleguide would also be good. There are variations that would be good to test that don't provide any visual benefit (changing `tagName` on a component or passing in additional/non-`variant` `className`s, for instance).
