### ISSUE TITLE
Mixed spaces and tabs in new-tag and new-component .jsx

### ISSUE THREAD

**Issue by elseloop** [connectivedx/fuzzy-chainsaw#139]
## Expected Behavior
Tags and Components created with the `new-tag` or `new-component` script should match the stated code style of the project.

## Current Behavior
When you run `npm run new-{tag,component} Whatever`, the resulting `Whatever.jsx` file is written with four space ___tabs___. Our `.editorconfig` asks for two ___actual spaces___ in `.jsx` files. The result is working in a mixed tab/spaces environment right from the jump.

## Possible Solution
Fix the the `[name].jsx` template to match expectations. (I‘m happy to do this, just, you know, _not right now_.)

## Steps to Reproduce (for bugs)
1. run `npm run new-tag PadThai`
2. open the resulting `PadThai.jsx`
3. note the mix of spaces and tabs
4. squint at screen in dismay

**Comment by krambuhl** [comment]
This should be added to the fix on #135 which already addresses a ton of mixed space/tab.  These templates are definitely the source of that mixture.

**Comment by elseloop** [comment]
@krambuhl Aw, crap. I missed that. High five!

**Comment by krambuhl** [comment]
This has been fixed and merged in #135 and #140
