### ISSUE TITLE
project JS test boilerplates

### ISSUE THREAD

**Issue by elseloop** [connectivedx/fuzzy-chainsaw#14]
- [x] unit tests
- [ ] functional tests (in-browser/DOM interaction whatnots)
- [x] linting

See #2 for some guidance

**Comment by krambuhl** [comment]
There are no great examples, but functional/integration testing can now be done using the `2.0` branch.  you are  no longer locked into to using enzymes `shallow` render, you can use the full `render` function if you want to run a stateful test.
