### ISSUE TITLE
Release candidate planning

### ISSUE THREAD

**Issue by krambuhl** [connectivedx/fuzzy-chainsaw#153]
We are nearing a FC 1.0 release candidate – which is super great! 🤘🔥🍖 

With a couple of CDX projects already kicked off using this codebase, we need to be careful that the changes we make before 1.0 don't throw big wrenches into folk's work in progress.  This ticket documents improvements that should be made before a 1.0 release and plans for future releases.

## Tasks for v1.0

🐓 🌞 🌱 🌴 🚀 👨‍🎤  DONE!

- :rocket: ~~Add linting for css and js in the webpack build process~~
- :rocket: ~~Add file path aliases in webpack (this will make traversing tags/components simpler)~~ (#162)
- :rocket: ~~Update file paths to use path aliases~~ (#162)
- :rocket: ~~Document update procedure for FC projects already in motion~~
- :rocket: ~~Add support for loading icons asynchronously~~ (#141)
- :rocket: ~~Add responsive webpack loader for img srcset~~ (#42)
- :rocket: ~~Fix output errors in styleguide's react tab~~ (#98)
- :rocket: ~~Add folder to copy vendor files to dist~~ (#165) 

## Tasks for v1.1

- Update component code style to use reacts defaultProps instead of destructured defaults
- Update npm scripts to provide clarity on the difference between webpack-dev-tools and standard webpack watch (#150)
- Update build tools to render components in the browser while developing (this will greatly improve the speed of development processes and enable hot module reloading)
- Remove `<Skeleton />` tag (to enable browser rendering, this will be replaced with a mustache-like template in a new `/templates` directory)
- Add form related tags (wip feature/form-tags)
- Add favicon webpack helpers (#124)
- Document `/tags` and `/components` codestyle
- Document `/pages` codestyle
- Update build tools to webpack 2

## Future releases
 
- Abstract rendering code to support different view engines (React, Vue, Elm)
- Update CSS code to [css-modules/css-modules](https://github.com/css-modules/css-modules) style to make interop simpler

**Comment by elseloop** [comment]
@krambuhl if you wanna point me toward the aliasing work you did recently, I can work through bullets 2 & 3 for 1.0 in the next few days.

**Comment by krambuhl** [comment]
@elseloop here is a ticket for your adventures! #162

**Comment by krambuhl** [comment]
This is way out of date. the 1.1 Tasks described above have all been addressed in the `2.0` branch
