### ISSUE TITLE
Don't clean before watching

### ISSUE THREAD

**Issue by kamsar** [connectivedx/fuzzy-chainsaw#154]
See https://github.com/connectivedx/fuzzy-chainsaw/blob/880677c2fbdaa3e30113da2d638e877d97e52792/gulpfile.js#L24

Because `clean:pre` is run before `watch`, this deletes any existing build files before starting watch.

This makes sense for a traditional `watch` that builds as files change. It does not make sense for `webpack-dev-server` which hosts all files in a virtual filesystem and afaik has no connection to the files on disk.

This creates issues because it removes styles other backend systems may rely on whenever the server watch is started, so you're forced to choose between writing code in the dev server or being able to refer to a styled backend site.

**Comment by krambuhl** [comment]
We can make that difference in the `npm run integration-watch` task.

The reason for deleting while running watch is to prevent false positives. for whatever reason, if a file returns a 404 from the virtual file system then the server will attempt to find the same file in the real filesystem.  Currently deleting `/dist` fixes this issue, but it might possibly be fixed using the webpack api in the `webpack-watch.js` file.

**Comment by kamsar** [comment]
Sounds like it should still do deletes then I guess. Integration watch fixes the major issue though (and it should retain clean as it performs a build afterwards).
