### ISSUE TITLE
Code highlighting

### ISSUE THREAD

**Issue by nicmarson** [connectivedx/fuzzy-chainsaw#156]
## Expected Behavior
Add code syntax styles based on language

## Possible Solution
Something like this, https://highlightjs.org.

**Comment by elseloop** [comment]
@nicmarson Are you intending this for the styeguide tabs or do you see a larger need for this?

**Comment by drolsen** [comment]
Would love to see syntax highlighting on styleguide tabs. 
A few times now on IHN while working with backend I've refereed to a part of code in a test, only to have a reply of, "hang on still looking hard to read".

**Comment by krambuhl** [comment]
@elseloop yes, this is for the styleguide code examples.

**Comment by jbascue** [comment]
I like highlightjs but I've only used it once. 

https://github.com/ccampbell/rainbow may also be a consideration. I've used it 3-4 times now on various projects and it's been fast, light, and easy. Kinda like me.

**Comment by elseloop** [comment]
(Results of quick look around while putting my kids to bed:) 

Most of the existing React syntax highlighter components require lifecycle events, which we do not have access to (yet), or use a method on the global scope that runs on load, which seems contrary to what we're doing. React Syntax Highlighter ([repo](https://github.com/conorhastings/react-syntax-highlighter) and [demo](http://conor.rodeo/react-syntax-highlighter/demo/)) looks pretty good, seems fairly lightweight, and exposes a functional/stateless component that fits into what's already happening here.

Unless you’d rather roll your own, in which case: go get 'em, tiger. 🏃 🐅
