### ISSUE TITLE
Loading MyFonts via JS

### ISSUE THREAD

**Issue by pgregorova** [connectivedx/fuzzy-chainsaw#165]
[MyFonts](https://www.myfonts.com) makes you host your purchased fonts and allow you to load them via CSS or JS with a file generated and provided by them. 

I haven't been able successfully load them like shown in the example within fuzzy chainsaw. 

Providing example files for how they implement their fonts using JS. 
[my-fonts-js.zip](https://github.com/connectivedx/fuzzy-chainsaw/files/742799/my-fonts-js.zip)

**Comment by krambuhl** [comment]
This will probably be solved by adding a `/source/vendor` folder that will copy assets into `/dist`.

@pgregorova I would only use the vendor folder to store the actual font files, the generated `Everence.js` file from my-fonts should still be required from the `scripts.jsx` entry file.
