### ISSUE TITLE
SVG generation does not play nicely with integration

### ISSUE THREAD

**Issue by blipson89** [connectivedx/fuzzy-chainsaw#168]
## Current Behavior

SVG icons 404 after being integrated with fuzzy chainsaw. The svgxhr plugin is putting the compiled `iconset.svg` in an invalid folder. When the page loads, it says it cannot find the file `http://sitename/assets/svgs/iconset.svg`. The file is **_actually_** located in `http://sitename/Project.Sitename/assets/assets/svgs/iconset.svg`

## Possible Solution

Temporary workaround, I've separated the SVG stuff ([similar to this](https://github.com/connectivedx/Tripwire/commit/1a4a67df7d39db3b100fa50a6644be9aa52f1ba0)) between the styleguide and the back-end app, and I'm using backend code to manually load the file and insert it onto the page. 

## Steps to Reproduce (for bugs)

1. you don't really have to do anything. The script just 404's after it's been integrated when it tries to load the icons.
2. go to the homepage, open up the network tab (or dev console) and see the 404

## Context

Had to do some extra steps that feel hacky to me in order to get icons to load. Ideally, I like to keep the integration as close to the source as possible.

## Your Environment

* Version used: latest?

**Comment by krambuhl** [comment]
It's loading a absolute path `/assets/svgs/iconset.svg` and it's being resolved to root.  I'll look into how we can prefix it – since this is loaded from the static bundle, it's a bit harder to fix pathing issue.
