### ISSUE TITLE
Clicking on the tabs bar outside of a tab clears out active panel in styleguide

### ISSUE THREAD

**Issue by elseloop** [connectivedx/fuzzy-chainsaw#169]
It's possible to deactivate all tabs in a style guide preview by clicking outside the tabs on the tab bar. Example:

![styleguide bug](https://cloud.githubusercontent.com/assets/1466832/22705287/ccc31902-ed1f-11e6-8be5-faced1965fc4.gif)

## Expected Behavior
The active tab should remain open unless a tab receives a click event.

## Current Behavior
The tab bar eats all clicks and deactivates all tabs, even is the target is the bar itself

## Steps to Reproduce (for bugs)
1. Go to any page in the style guide
2. click on the tab bar to the right of the tabs
3. all panels collapse
4. 😞

**Comment by krambuhl** [comment]
😿
