### ISSUE TITLE
[Request] No styleguide build option

### ISSUE THREAD

**Issue by blipson89** [connectivedx/fuzzy-chainsaw#179]
Feature request: ability to build fuzzy chainsaw with the minimum for production integration. 

Jenkins spends a bunch of time building out all the `.Test.jsx` files and compiling the entire styleguide on production, however it's just thrown away. None of that is used on production. Could we add an option, such as `npm run production --quick` or something that cuts out anything not needed for an actual production deployment?

My goal is to try to cut back on overall build/deployment times on the build servers.

**Comment by krambuhl** [comment]
Notes from slacking with Ben.  static html and test files are not required for production build, only the css, js, images, fonts, and icons defined in `/assets`.  This will go hand-in-hand with `speedy-dev` branch currently in progress.

**Comment by krambuhl** [comment]
This has been resolved on the `2.0` branch.

There are `build:ci` and `production:ci` commands that skip static html generation and styleguide code.
