### ISSUE TITLE
Icon tag functionality breaks after building project

### ISSUE THREAD

**Issue by bstaruk** [connectivedx/fuzzy-chainsaw#213]
## Current Behavior
Icons do not work after building the project. The console error found is:

`XMLHttpRequest cannot load file://assets/svgs/iconset-1499259840283.svg. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`

## Steps to Reproduce (for bugs)
1. Clone `Master` branch (as of 7/5/2017)
2. Run `yarn` in project root
3. Run `npm run production` to build project
4. Open built project in a web browser (with debugged/console open)
5. Navigate to Styleguide > Tags > Icon

**Comment by krambuhl** [comment]
This is related to deploying a site on a non-root environment. this should be outputing a relative path or and absolute path based on `BASE_URL` env var

**Comment by krambuhl** [comment]
@bstaruk This should now be solved on the FC1 `develop` branch.  Check that solution out and close this issue if things are functioning as expected.

**Comment by bstaruk** [comment]
Confirmed working! Thank you!
