### ISSUE TITLE
Composition scaffolding builds to wrong directory

### ISSUE THREAD

**Issue by bstaruk** [connectivedx/fuzzy-chainsaw#255]
When `npm run new:composition` is run, the scaffolding feature puts the new composition in `/source/elements/composition` (missing the "s" at the end of "compositions").

## Expected Behavior
Compositions should be stored in `/source/elements/compositions`

## Current Behavior
Compositions are stored in `/source/elements/composition`, but since this is the wrong directory the composition won't be visible in the styleguide

## Possible Solution
Change `/gulpfile.js:97` from `dest: 'composition'` to `dest: 'compositions'`

## Steps to Reproduce (for bugs)
1. `git clone https://github.com/connectivedx/fuzzy-chainsaw`
2. `yarn`
3. `npm run new:composition Test`
4. `npm run build:dev`

**Comment by krambuhl** [comment]
This is fixed in `2.0.1` release. 

If you'd like to review, this PR solves the issue https://github.com/connectivedx/fuzzy-chainsaw/pull/267

**Comment by krambuhl** [comment]
This is fixed in `2.0.1` release. 

If you'd like to review, this PR solves the issue https://github.com/connectivedx/fuzzy-chainsaw/pull/267
