### ISSUE TITLE
Missing enhanced-resolve module

### ISSUE THREAD

**Issue by drolsen** [connectivedx/fuzzy-chainsaw#256]
Fresh version of FC2.0 on Windows wont run watch or build. Appears to be a missing **enhanced-resolve** module not found in FC package.json. After running "npm install enhanced-resolve", my watch and builds all started working as anticipated.

Lets make sure we don't forget to include this.
Thanks!

**Comment by krambuhl** [comment]
this explains an issue we were seeing earlier! the yarn.lock has the enhanced-resolve module but the package.json does not.  I have a list of bugs #253 that will all be resolved in 2.0.1 (hopefully in the next 3 days or so)

**Comment by krambuhl** [comment]
This is fixed in `2.0.1` release. 

If you'd like to review, this PR solves the issue https://github.com/connectivedx/fuzzy-chainsaw/pull/267
