### ISSUE TITLE
Scaffolding name vs. CSS name

### ISSUE THREAD

**Issue by drolsen** [connectivedx/fuzzy-chainsaw#257]
Our scaffolding factory validates for PascalCase, so I assume that naming components and tags as title case vs. all lower case is allowed (something I do heh). 
However, our scaffolding (both stateful and stateless) applies a title case version of component's name to base classes in CSS for said newly created component.

## Expected Behavior
No matter how you name new component (ex: "Collage" or "collage"), the resulting base CSS classes for new component should always be lowercase "collage collage--${variant}", not "Collage Collage--${variant}".

## Current Behavior
If you pass a title case name to npm run new:component, the base classes in both .jsx and .css are also title case and not lowercase.

## Possible Solution

We don't want to lower case the existing name prop being passed to scaffoling template cause we like most things to be named exactly as entered. Instead, make new prop to have scaffoldComponent return with:
**/build/scaffold-factory.js**
```javascript
/*
  This provides a factory that returns a gulp task
  for scaffolding directories.
*/

const gutil = require('gulp-util');
const path = require('path');
const minimist = require('minimist');
const chalk = require('chalk');
const dopl = require('dopl');

const { source } = require('./lib/path-helpers');


const scaffoldComponent = ({
  name,
  src,
  output
}) => {
  if (!/^[A-Z][A-Za-z]+$/.test(name)) {
    gutil.log(chalk.bgRed('The name should be in PascalCase.'));
    process.exit(1);
  }
  
  classBase = name.toString().toLowerCase();

  return dopl({
    src,
    output,
    data: {
      name,
      classBase
    }
  });
};


module.exports = ({ src, dest }) => () => {
  const argv = minimist(process.argv.slice(2));

  return scaffoldComponent({
    name: argv.name,
    src: path.resolve(__dirname, 'scaffolding', src),
    output: source('elements', dest, argv.name)
  });
};
```

**build/scaffolding/[stateful or stateless]-component/[name].css**
```css
.{{classBase}} {
  /* Put rules here */
}
```
**build/scaffolding/stateless-component/[name].jsx (also stateful-component version)**
```javascript
export const {{name}} = (props) => {
  const {
    tagName: Tag,
    className,
    variant,
    children,
    ...attrs
  } = props;

  const classStack = FcUtils.createClassStack([
    '{{classBase}}',
    `{{classBase}}--${variant}`,
    className
  ]);

  return (
    <Tag className={classStack} {...attrs}>
      {children}
    </Tag>
  );
};

{{name}}.defaultProps = {
  tagName: 'div',
  variant: 'default'
};

{{name}}.propTypes = {
  tagName: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.element,
    PropTypes.func
  ]),
  className: PropTypes.string,
  variant: PropTypes.oneOf(['default']),
  children: PropTypes.node
};


export default {{name}};
```

I admit, "classBase" is not the most descriptive name but it's what I've use for the time being.

**Comment by krambuhl** [comment]
One of the norms we are trying to push with FC2 is to keep naming identical between CSS and React, so if I understand you correctly, this is working as expected.  

The reason for this was to have a consistency in naming so when a dev runs into a css selector they know to look in that component folder.  it also makes Find/ReplaceAll on a component name a bunch easier.

This means that a React component called `SuperBigBox` will be in a file called `SuperBigBox.jsx` and the css class will be `.SuperBigBox` in a file called `SuperBigBox.css`.  consistency is nice.

**Comment by elseloop** [comment]
To add to that a little, there is a convention on React to name components using Pascal case as a way of differentiating them from native elements. (This is baked into the core of React—see [this page in the docs](https://facebook.github.io/react/docs/jsx-in-depth.html#html-tags-vs.-react-components) for some additional info.) Since we have no real options on that front, we decided a while ago to normalize around that convention for all the reasons @krambuhl laid out. Which is also to say that you should _always_ be using Pascal case when creating your components.

**Comment by krambuhl** [comment]
Closing issue unless we are totally missing something here.
