### ISSUE TITLE
Rendering fails in IE11 for some default tags

### ISSUE THREAD

**Issue by bstaruk** [connectivedx/fuzzy-chainsaw#273]
On a fresh clone of Fuzzy Chainsaw v2.0.2, trying to view certain default tags (ex: Media) causes a rendering issue on IE11. Specifically, the page fails to load and instead shows a blank white page. An error appears in the console log which says:

`Object.keys: argument is not an Object`

Other affected tags include: List, Rhythm & Richtext

## Steps to Reproduce (for bugs)
1. Clone a new copy of Fuzzy Chainsaw
2. Run `yarn` in the project root to initialize it
3. Run `npm dev` to get the project running in webpack dev server
4. Navigate to a broken tag (ex: Media) in the styleguide

## Your Environment
* Version used: FC 2.0.2
* Browser Name and version: Internet Explorer 11
* Operating System and version (desktop or mobile): Windows 10 (fully updated)

## Possible Solution
Will investigate and log any findings as comments on this issue.

**Comment by krambuhl** [comment]
Still looking at this, just wanted to provide an update here.  It appears to be related to IE and the process to clean example JSON.  I have a solution going for `Media`,  `List`, and `Rhythm`, but still struggling to solve `RichText`.

**Comment by krambuhl** [comment]
Fixed in 2.0.3 release.
