### ISSUE TITLE
[LP Integration] Production Builds

### ISSUE THREAD

**Issue by blipson89** [connectivedx/fuzzy-chainsaw#275]
LP executes the `production` command of fuzzy chainsaw. The problem is, as part of the production build process, LP cleans/blows away the output directory that contains FC's DLLs. FC's `production` command won't rebuild them, but `full:production` will.

## Expected Behavior

I need `production` to build the DLLs

## Current Behavior

it does not

## Possible Solution

I made this change to the `package.json` of the project I'm currently on.
![image](https://user-images.githubusercontent.com/4602966/30278325-18557a2e-96d8-11e7-8ecf-bd4d631923b0.png)

## Context

the LP stack will never actually need to execute `quick:production`. I left that in there in case it was necessary for compatibility on FC's end. If it is not, maybe it makes sense to just make `production` be `full:production`?

**Comment by bstaruk** [comment]
https://github.com/connectivedx/fuzzy-chainsaw/pull/276

I have submitted a pull request with documentation behind the reasoning for the proposed changes.

Will work today/tomorrow on getting the rest of the FED team involved in this discussion to keep the ball rolling.

**Comment by bstaruk** [comment]
Closing issue, as it was resolved with the 2.1.0 release.
