### ISSUE TITLE
Add active state to theme links on "tag" or "component" page

### ISSUE THREAD

**Issue by pgregorova** [connectivedx/fuzzy-chainsaw#284]
When viewing a tag or a component that may have theme variable, it's not obvious which theme is being active when toggling between them. 

## Expected Behavior
It would be helpful to have active state set for active theme link (under tag or component heading) for easier visual cue.

## Current Behavior
At the moment there isn't an active state, links change from unvisited to visited, hover or focus state. 

## Possible Solution
An active class could be toggled on click and styles could be easily overwritten (possibly remove underline and cursor to change to arrow, or remove the anchor altogether when active?)

## Steps to Reproduce (for bugs)
1. Enable theming
2. Choose any tag or component
3. Click on either links below tag or component's heading

![2017-10-23_10-29-37](https://user-images.githubusercontent.com/124532/31897929-c7607a4a-b7e5-11e7-8716-6d3f44df676f.png)

## Context
This would be mainly improvement from user's perspective to help provide visual cues on which theme is active on a specific tag or component.

**Comment by drolsen** [comment]
@elseloop has added the appropriate font-weight class to the active theme link of any given styleguide page.

Thanks!

**Comment by elseloop** [comment]
@drolsen Just as an FYI for the future, this issue would have closed automatically once the work in my PR was merged into master, as it had "Fixes #284" in its description ([documentation](https://help.github.com/articles/closing-issues-using-keywords/).

![the more you know](https://bukk.it/themoreyouknow.gif)

**Comment by pgregorova** [comment]
THANK YOU @elseloop for such promptness in addressing this! :)
