### ISSUE TITLE
Example links are inline without spacing and uppercase

### ISSUE THREAD

**Issue by pgregorova** [connectivedx/fuzzy-chainsaw#307]
## Expected Behavior
The best it can be viewed on `Button` tag within `master` branch where the links are vertically stacked

## Current Behavior
I have noticed that all example links in styleguide are inline, uppercase and without any spacing around it.

## Steps to Reproduce (for bugs)
The best it can be viewed on `Button` tag within `develop` branch

What seems to be the problem is that all the example links in `master` have `.SgStyleguide__example-link` passed to them but in `dev` branch that link gets replaced with  `.SgStyleguide__theme-link`, which should be applied to theme links only and not the ones meant for examples.

**Comment by bstaruk** [comment]
I believe this issue can be fixed by changing the `getLinkClassing` function in `SgStyleguide.jsx` to:

```js
const getLinkClassing = (theme) => {
  if (theme.id === getActiveTheme(global.location)) {
    return 'SgStyleguide__theme-link SgStyleguide__theme-link--active';
  } else if (theme.id) {
    return 'SgStyleguide__theme-link';
  }
  return 'SgStyleguide__example-link';
};
```
