### ISSUE TITLE
Set No-Index/No-Follow on Styleguide

### ISSUE THREAD

**Issue by blipson89** [connectivedx/fuzzy-chainsaw#315]
## Expected Behavior

Meta tags setting `no-index` and `no-follow` should be set for the styleguide index.

## Current Behavior

Styleguide indexes can be crawled by search engines

## Possible Solution

http://www.robotstxt.org/meta.html

## Context

The styleguides are still accessible on production. However, we don't want them crawled by search engines.

**Comment by drolsen** [comment]
This has been fixed with the 2.4.6 release.
Thanks!
