### ISSUE TITLE
"page.pageType" not working as expected

### ISSUE THREAD

**Issue by pgregorova** [connectivedx/fuzzy-chainsaw#352]
There seems to be a bug when it comes `page.pageType = 'index'` and `page.pageType = 'styleguide'`

## Expected Behavior
When I add a new page inside `pages/styleguide` folder and set  `page.pageType = 'styleguide'`, I would expect for it show up under section in Table of Contents labeled as "Styleguide", below Home.  

## Current Behavior
Let's say I add a new page under styleguide and set pageType to *styleguide*, I would expected it to show under Styleguide, but it keeps getting added under *Pages* instead with "Styleguide" label before it.

**Comment by bstaruk** [comment]
Resolved by #355
