### ISSUE TITLE
Conditional includes

### ISSUE THREAD

**Issue by elseloop** [connectivedx/fuzzy-chainsaw#38]
(Literally copy/pasting from comments on #3)

Speaking with @devinrayolsen about the common need to add dev-only stylesheets to projects, for secondary applications of the codebase or other stand-alone uses like, for example, off-site theming deliverables (PGE and OHSU have several examples of these), he floated an idea of being able to skip partials or other stylesheets during production builds, via a comment or front-matter like block in the file itself. This would save you from having to go into the build to delineate multiple build sources/outputs and allow your focus to remain in the files you're working in, without having to break out and touch the build or to create increasingly complicated folder structures to denote the various build needs. (We were talking specifically about styles, but this could easily be applicable to JS as well I imagine.)

A quick Google didn't lead me to any existing PostCSS or Gulp utilities to pull this off (which leads me to worry I'm not thinking this through entirely), but I wanted to get the idea down in this issue while it was still fresh in my mind.

(from @krambuhl)

Can this be read as the need for conditional imports/requires? Like ENV=production outputting a different stylesheet/js from ENV=develop?

**Comment by kamsar** [comment]
As all stylesheets are pulled in via `bundle.jsx`, e.g.

`require.context("./tags/", true, /\.css$/);`

that's JS and thus you can conditionalize your heart out

**Comment by elseloop** [comment]
This issue was opened before we had anything in place. It no longer makes any sense. Or was solved incidentally, depending on how you look at it. Anyway: closing it as unnecessary.
