### ISSUE TITLE
include Service Workers boilerplate?

### ISSUE THREAD

**Issue by elseloop** [connectivedx/fuzzy-chainsaw#41]
From what I can gather, we can pretty painlessly generate this as part of the build using [sw-precache](https://www.npmjs.com/package/sw-precache) & [sw-toolbox](https://www.npmjs.com/package/sw-toolbox) and really minimal config. Which would be, you know, both awesome and

![magic](http://bukk.it/magic.gif)

**Comment by krambuhl** [comment]
Both of these seem like they could handle this issue: https://github.com/NekR/offline-plugin or https://github.com/oliviertassinari/serviceworker-webpack-plugin

**Comment by krambuhl** [comment]
These are now automatically generated on the `2.0` branch.
