### ISSUE TITLE
Support for responsive images

### ISSUE THREAD

**Issue by elseloop** [connectivedx/fuzzy-chainsaw#42]
Goals:
- [x] programmatically resize images to some set ranging from minimum/low-res size up to largest high-res
- [ ] OPTIONAL: hook into CMS to be able to run this against user uploaded images as part of publish event?
- [ ] include [Picturefill](https://scottjehl.github.io/picturefill/) or some other `srcset`/`<picture>` polyfill ([definitely still needed, imho](http://caniuse.com/#search=picture))
- [ ] Handlebars helper for more easily writing `<picture>` elements in all [its weirdness](https://scottjehl.github.io/picturefill/#using-picture)

**Comment by krambuhl** [comment]
https://www.npmjs.com/package/responsive-loader
