### ISSUE TITLE
SVG template helper(s)

### ISSUE THREAD

**Issue by elseloop** [connectivedx/fuzzy-chainsaw#47]
The SVG task (#39) generates a sprite but doesn't then _do anything_ with it. This is a placeholder to remind us to write the something that needs to be done once our approach to templates is stable. We will need a Handlebars helper to quickly write `<use>`  tags and (maybe) a separate module to AJAX the resulting sprite into the document on load. That AJAX module could likely be something like the following:

``` javascript
module.exports = (spritePath) => {

    if (typeof spritePath !== 'string') {
        throw "spritePath must be a string";
    }

    const ajax = new XMLHttpRequest();
    ajax.open("GET", spritePath, true);
    ajax.send();
    ajax.onload = function(e) {
        const div = document.createElement("div");
        div.style.height = '0';
        div.innerHTML = ajax.responseText;
        document.body.insertBefore(div, document.body.childNodes[0]);
    };
};
```

**Comment by elseloop** [comment]
Something like [this helper](https://github.com/cloudfour/core-hbs-helpers/blob/master/lib/svg.js) FPO svg helper from Drizzle would be nice too.

**Comment by krambuhl** [comment]
We might want to rescue this gulp plugin from FC1... I'm not sure yet.  If this can still create the sprite, we can suck it up in the base component and create a generic "Svg" component that can set the svg use property.

**Comment by krambuhl** [comment]
This was completed in #93
