### ISSUE TITLE
Review old issues and close or update to reflect codebase updates.

### ISSUE THREAD

**Issue by stoff** [connectivedx/fuzzy-chainsaw#50]
All tasks previous to this were written for codebase reflected in [pointy pompadour](https://github.com/connectivedx/fuzzy-chainsaw/releases/tag/v0.1).  We'll need to vet all old tasks and determine if they are still pertinent.  Pertinent tasks may need to be updated to reflect new codebase; all other tasks should be closed.

**Comment by krambuhl** [comment]
I've taken a 2nd pass over the remaining tickets.  What dan closed was good and the rest seem like things we still want, but might have a different look inside of a webpack world.  

Going to close 🍔
