### ISSUE TITLE
web dev server spawn on windows

### ISSUE THREAD

**Issue by stoff** [connectivedx/fuzzy-chainsaw#52]
Copied from https://github.com/krambuhl/hairy-machete/issues/3.

**Original Description:**
windows cannot find webpack-dev-server when running `npm run watch`

**@krambuhl reported a change:**
I've changed the method of calling this spawn call, please give it a try @devinrayolsen and see if you're able to start the watch task using `npm run watch`
ref https://github.com/krambuhl/hairy-machete/issues/3#issuecomment-255608509

**Comment by kamsar** [comment]
Going to shutter this in favor of #90 which has a fix in progress.
