### ISSUE TITLE
FC integration tasks

### ISSUE THREAD

**Issue by kamsar** [connectivedx/fuzzy-chainsaw#63]
Here are the steps to integrate FC with other larger projects at this time:

- Copy a clone of FC to the target project
- Remove the `.git` directory
- Remove the `.github` directory
- Disable `root=true` in `.editorconfig`
- Change the input and output paths for the frontend artifacts as needed, e.g. in package.json (LP)

     "directories": {
         "source": "./Project.Prototype/",
         "output": "../../../website/Project.Prototype/dist"
      }

- (LP specific) register your gulpfile directory with the global `build\config.json` so that the global build and watch scripts will interact with it
- (LP specific) augment the gulpfile.js with the standard expected tasks interface, even if some of them do nothing (see `doc\project gulpfile API example.js` in LP)

**Comment by kamsar** [comment]
LP now has documentation to the effect of the above. Since it's not public I won't link to it here.

Feel free to document this within FC as well, or just close this if you hate documentation.

https://youtu.be/CtFLzGRfVnA?t=7s

**Comment by elseloop** [comment]
This documentation is [here in LP](https://github.com/connectivedx/legendary-pancake/blob/master/doc/Developer%20Documentation/Frontend%20Developers.md#integrating-fuzzy-chainsaw-builds). We've agreed that's where this should live, so closing this.
