### ISSUE TITLE
Something is too greedy when reading component files

### ISSUE THREAD

**Issue by kamsar** [connectivedx/fuzzy-chainsaw#67]
The stack traces were singularly unhelpful, but something appears to be trying to shoot every file through webpack.

To replicate this, as an example:
* Create `source/components/product-description.cshtml`
* Add, say, `@foo` to the body
* `npm run build`

💥 

![image](https://cloud.githubusercontent.com/assets/103677/19856406/83e0f6be-9f36-11e6-826a-b7130354edd4.png)

This same thing also occurs even with a README.txt file.

**Comment by krambuhl** [comment]
This has been fixed in #76

**Comment by krambuhl** [comment]
The fix avoids cshtml, cs, and csproj files, if we want to ignore txt files, we'll need to add that filetype
