### ISSUE TITLE
Use relative paths in HTML output

### ISSUE THREAD

**Issue by kamsar** [connectivedx/fuzzy-chainsaw#68]
If we're emitting all the HTML to the output directory, it'd be handy if we could browse the output without binding a site directly to the output root.

For example in LP the FC output would reside at something like `/Project.FooMonkeys/index.html`, but because all paths are absolute the links would all be broken (e.g. `/assets/foo.css` as opposed to `../assets/foo.css`).

If this is a huge thing to implement then I can live without it.

**Comment by kamsar** [comment]
This will also cause problems when posting to the UI server where paths are not at the root for templates.

**Comment by krambuhl** [comment]
I will make an effort to address this in my next pass.

**Comment by stoff** [comment]
@kamsar regarding UI server, is it worth having a conversation with IT about making the server work more like a real-world environment?  This has come up in the past as a pain point, and it would be awesome if we could change the server to be less idiosyncratic, rather than tweaking our tool to be ... more idiosyncratic.

**Comment by kamsar** [comment]
@stoff how is it not all that real-world? For PHP projects maybe less so but it's hosted on IIS with the usual array of plugins and MIME types a Sitecore kit would have. Or so I think, it is pretty old 😁 

The pathing issue will affect more than just UI; for example a dev wanting to preview the current markup on a LP install at say `/Project.Foo/assets/index.html` would run into the same problem.

**Comment by pgregorova** [comment]
@krambuhl, could we make this a priority as I have a deadline on 11/29 to show things to a client, pretty please? :)

**Comment by krambuhl** [comment]
@pgregorova absolutely!  I started a branch last night with a fix when I realized Devin was trying to use UI server already.  I hope to have this PRed by end of day

**Comment by stoff** [comment]
@krambuhl thank you
@kamsar good point, but on most projects aren't there redirect rules in place to cause assets to serve from root?  what if we included a web.config with redirects to make it possible to use consistent pathing?

**Comment by kamsar** [comment]
@stoff  wouldn't it be easier to just emit relative paths so it works anywhere instead of band-aiding the issue with a hardcoded root path?
