### ISSUE TITLE
File name style

### ISSUE THREAD

**Issue by krambuhl** [connectivedx/fuzzy-chainsaw#70]
It seems to be the format in LP to use pascal case for components, I started using bem naming conventions.  This makes sense for css but not as much for React and js dependencies. 

### Pascal Camel Case

```
-- Components
  -- MySweetComponent
    -- MySweetComponent.jsx
    -- MySweetComponent.css
```

```js
import MySweetComponent from './MySweetComponent';
```

```css
.my-sweet-component { }
```

### Slug Style

```
-- Components
  -- my-sweet-component
    -- my-sweet-component.jsx
    -- my-sweet-component.css
```

```js
import MySweetComponent from './my-sweet-component';
```

```css
.my-sweet-component { }
```

**Comment by elseloop** [comment]
Am I correct in believing this to be resolved and ready to be closed? (—Housekeeping)

**Comment by kamsar** [comment]
No the existing elements need to be renamed to the convention.

**Comment by elseloop** [comment]
Right, of course. That's what I get trying to be productive before 7am.

**Comment by krambuhl** [comment]
I was waiting for the bigger changes to merged before making this change. Starting this task now.

**Comment by krambuhl** [comment]
Opened #80 to make this change.

**Comment by kamsar** [comment]
#80 merged successfully, shuttering this issue
