### ISSUE TITLE
PR #76 regressions

### ISSUE THREAD

**Issue by elseloop** [connectivedx/fuzzy-chainsaw#78]
Looks like #76 went directly from a `bugfix` branch straight into `master`, sidestepping `develop`, and missed some earlier PR's made against `develop` and/or overwrote some previous commits PR'd into `develop`.

I see regressions to changes made in #75, at least, but rather than patch that alone, I wanted to open this in case there’s other work that’s been affected.

**Comment by krambuhl** [comment]
My fault, oops. I will have to take a look later.  Can someone please make the default branch develop and protect master? Save me from myself

**Comment by kamsar** [comment]
Default branch is now develop. Master is protected, but I didn't enable forced PR review or anything.

**Comment by krambuhl** [comment]
64abe8e ec78279 are the offending commits.  They are both behind the develop head, so I think we will be able to merge develop into master without any loss.   I made a test merge on my local repo with success, but I will open a real PR to make a release.

**Comment by krambuhl** [comment]
Both of these pull requests sidestepped peer-review and got merged directly into master.  We should use our shared eyes to avoid these type of mistakes and not feel rushed to merge our PRs immediately.  If we want to get something merged quickly, we should ping via slack.

![image](https://cloud.githubusercontent.com/assets/1424368/19913980/559c5634-a064-11e6-85fd-717676b3e460.png)

**Comment by krambuhl** [comment]
#79 should address getting master in sync. once that has been merged successfully, we will need to make sure that changes merged into master are pulled back out into the develop branch.

**Comment by elseloop** [comment]
I refuse to be shamed for committing a single question mark in a README directly to master. Refuse, I tell you. 😜

**Comment by kamsar** [comment]
#79 is merged and I also merged master back into develop
