### ISSUE TITLE
Automatically include css variables

### ISSUE THREAD

**Issue by krambuhl** [connectivedx/fuzzy-chainsaw#82]
Right now, to use global css custom selectors you need to manually import variables  `@import "./variables/index.css";`.  since `variables/index.css` does not have actual output, It would be more convenient to prefix component css with this import automatically.  

This would also remove `@import` statements referencing local files, which has a different build semantic (`@import` inside a css file is a post-css import, not a webpack import).  I would like to remove references, so new users won't confront this subtle difference.

**Comment by kamsar** [comment]
Closing in favour of #94
