### ISSUE TITLE
A proposal to reorganize the filesystem

### ISSUE THREAD

**Issue by kamsar** [connectivedx/fuzzy-chainsaw#87]
Based on reviewing the build system I had some ideas/notes that I feel (disagreement accepted) would improve the overall discoverability and maintainability of FC.

1) Remove defaults from shared webpack configs' function args [e.g.](https://github.com/connectivedx/fuzzy-chainsaw/blob/develop/build/webpack.static.js#L9) (and pass in all parameter values from `webpack.config.js`, removing params that are not used as the config object can always be changed later)
2) Document each webpack config file with (a) what it's for (b) what it depends on and (c) common ways you may wish to customize it (I did this already in #86)
3) Rename 'postcss-pack.js' to 'postcss.plugins.config.js' and add comment (done in #86 but not renamed) that it's the global postcss config for all webpacks that utilize postcss.
4) Refactor folder structure to minimize root file additions and make it more obvious when integrated what is FC and what is not, bring config closer to the code that calls it, clarify the roles of various webpack config files more explicitly on the filesystem, modularize some things, and make the gulpfile as project-mutable as possible without breaking FC upgrade merges. Proposed restructuring:

```
- build
    - tasks (contains gulp non-root tasks and supporting files, and aligns with LP build setup)
        - clean
            - pre.js
            - post.js
        - build
            - webpack.js
            - webpack-production.js
            - webpack-config (moves webpack config next to tasks that execute it for clarity when finding it)
                - shared
                    - webpack.assets.js (was .browser.js - matches output folder name this way)
                    - webpack.pages.js (was .static.js - matter of opinion, static was confusingly short, also maybe 'static-site-generator'?)
                    - webpack.tests.js
                    - webpack.styleguide.js
                    - postcss.plugins.config.js
                - webpack.config.js
                - webpack.config.production.js
        - watch.js (move kicker code here; add 'watch' folder if > 1 task or needs libs)
        - scaffolding
            - new-tag.js
            - new-component.js
            - templates
                - scaffold-component.js
                - component-template (directory)
    - lib (misc shared JS funcs)
        - webpack-errorhandler.js
        - (possibly helper funcs in webpack.config.js in a lib file)
    
- gulpfile.js
    - can now turn into requireDir(./build/tasks)
    - wire up root tasks using sub-tasks in build
    - enables projects (e.g. LP which requires additional root tasks) to add on/change gulpfile without causing merge headaches with FC updates```

The above table does not contain every file in FC - unlisted things, like all source items, I am not proposing any alterations on. I'm fine making the changes but did not want to make a big unexpected PR to scare people or cause argument and wasted work time :)

**Comment by krambuhl** [comment]
I like some of this.  

1. There are defaults used in a couple places for a reason.  In most of the configs `outputScript = '/tmp/bundle.js` or `outputStyle = '/tmp/bundle.css'` is defined by default.  this is because webpack will always create both of those files but we might only be interested in one, the others get pushed to the tmp directory and deleted after webpack is complete.  

2. There is a ton of common config between the 4/5 webpack files, I'd like to pull this out into a `webpack.shared.js` file that the other builds extend.  

3. super.

4. There are a couple sections worth discussing.  I don't like that there are 3 different words used to describe lib/util type files.  

- `build/lib` 👍 
- `build/tasks/build/webpack-config` 
- `build/tasks/build/webpack-config/shared` 👎 

What's the differences between webpack.config.js and webpack.js above?

This is what I would expect to see in the build section:  

```
- webpack (having a build directory in the build directory is confusing, this is where webpack stuff happens)
    - webpack.js
    - webpack-production.js
    - lib (can we use lib consistently?)
        - webpack.browser.js (I called this browser because it's only in charge of `bundle.css` and `bundle.css`, I think we should call this webpack.bundle.js)
        - webpack.static-generator.js (Pages is a confusing name, this controls the config for both `source/pages` and styleguide related commands)
        - webpack.tests.js
        - webpack.styleguide-generator.js
        - postcss.plugins.config.js
```

This is what I would expect in the scaffolding section.  Having the code for scaffolding inside the templates directory feels odd.  

```
- scaffolding
    - new-tag.js
    - new-component.js
    - lib
        - scaffold-component.js
    - templates
        - component-template (directory)
```

or 

```
- scaffolding
    - new-tag.js
    - new-component.js
    - component
        - scaffold.js
        - template (directory)
```

**Comment by kamsar** [comment]
> What's the differences between webpack.config.js and webpack.js above?

`webpack.js` is the gulp task that fires off webpack as opposed to the actual config of it

**Comment by kamsar** [comment]
I'm going to leave this one alone. I still think it's worth doing but I don't have the time for it.

**Comment by krambuhl** [comment]
This has been done.
