### ISSUE TITLE
Build scaling

### ISSUE THREAD

**Issue by kamsar** [connectivedx/fuzzy-chainsaw#95]
Webpack is now taking 38 seconds to run a build:

![image](https://cloud.githubusercontent.com/assets/103677/20061070/0e2c4496-a4b3-11e6-92f0-1a6e89ea1fdd.png)

Not sure if my machine is just feeling terrible this morning (low CPU stats dispute this hypothesis), or if something has recently happened that bloated the build time. I've been used to seeing ~8 sec previously, which is still not awesome.

I'm wondering though if this will scale well to a good sized site with potentially several hundred tags and components.

**Comment by kamsar** [comment]
This was on https://github.com/connectivedx/fuzzy-chainsaw/commit/a8378fd8356ecba8f46fa2960c773567b7c643c2 btw, and I tested prior to merging SVG PR as well and the timings were similar.

**Comment by kamsar** [comment]
Traced: this appears to be due to the addition of uglify with source maps. And the fact that it looks like `webpack.production.js` is applying to every build even not production.

I suspect we may have some pass-by-reference shenanigans going on here.

**Comment by kamsar** [comment]
Uglify off: 11 sec
Uglify on, sourcemaps: 38 sec
Uglify on, no sourcemaps: 25 sec

Uglify is also being loaded onto the tests config which is probably too aggressive.

**Comment by kamsar** [comment]
The CLI is faster because it's not using the gulpfile that is requiring the production config as well as the dev config. Thus it's not uglifying. It appears that the `config` object is a reference and thus as soon as production is required it modifies the one config object to rule them all. Needs some object.assign or something :)

**Comment by kamsar** [comment]
Ok this is due to the output of `require()` being a static reference. In other words, everyone who does `require('./webpack.config')` gets _an instance of the same array_. Thus, when the production config starts fooling with the config object, it's changing the resultant object of `require('./webpack.config')` _for everyone_ because it's one reference.

There are two solutions I can see:
1) Turn `webpack.config.js` into a factory (proven to fix the problem), e.g. note how the below turns the configs and exports into factory functions (it'd make sense to turn it into a single factory export imo if we use this). The downside is that `webpack` CLI will probably not understand that it needs to invoke the function returned from the config file, but you probably ought not to be doing that anyway. Turning this into a factory function means that each require will invoke the factory to get its own unique copy of the config.

```/*
 *
 * CREATE WEBPACK CONFIGURATIONS
 * The shared base configurations imported earlier are augmented with paths and specific details here.
 *
 */
const renderPages = () => staticConfig(baseOutput({
  entry: dirs.source + 'RenderPage.jsx',
  locals: { components, tags },
  paths: glob.sync(dirs.source + 'pages/**/*.jsx')
    .map(getDeepName(`${dirs.source}/pages`))
    .map(page => `${page}.html`),
}));

const renderStyleguide = () => styleguideConfig(baseOutput({
  entry: dirs.source + 'RenderStyleguide.jsx',
  locals: { components, tags },
  paths: styleguides.map(page => `styleguide/${page}.html`)
}));

const styleguideBundle = () => browserConfig(baseOutput({
  entry: dirs.source + 'styleguide.jsx',
  outputScript: '/assets/styleguide.js',
  outputStyle: '/assets/styleguide.css'
}));

const browserScript = () => browserConfig(baseOutput({
  entry: dirs.source + 'main.jsx',
  outputScript: '/assets/bundle.js'
}));

const browserStyle = () => browserConfig(baseOutput({
  entry: dirs.source + 'style.jsx',
  outputStyle: '/assets/bundle.css'
}));

const componentTests = () => testsConfig(baseOutput({
  entry: dirs.source + 'tests.jsx',
  outputScript: '/tmp/tests.js',
  reporter: 'tap-min'
}))


/*
 *
 * EXPORT ALL CONFIGURATIONS
 * Consumers of this config (e.g. gulp) will pass these to webpack for execution.
 *
 */
module.exports = () => [
  browserScript(),
  browserStyle(),
  renderStyleguide(),
  styleguideBundle(),
  renderPages(),
  componentTests()
];
```

2) Make a deep copy of the array in `webpack.production.config.js` before fooling with it.

I'm inclined more towards (1) because doing that is the same convention that the base configs (e.g. static) are using - factory functions.

**Comment by krambuhl** [comment]
Making the shift to a factory approach is the most sane to me.  we can have a shared factory that both configs can call.

## Notes
- now that RenderStyleguide and RenderPages are using the same code upstream.  merging these two into a single config might be possible
- browser scripts and browser styles can't be merged without inflating the dependency tree of the scripts or losing import ordering on styles.  There is no way that I know of to run loaders only with specific entry file.  we want .css files to be a null loader on scripts.jsx and .css files to be a extract text loader on styles.css
- component tests have the same issue as browser scripts, testing requires a different set of loaders than compilations
- styleguide is able to output js and css together because we are requiring css directly and not making use of jsx files (which also include their css dependencies).  

## Also, for reference..

Here are perf times for each config individually.  

config | exec time
--- | ---
browserScript | 3.103s
browserStyle | 3.197s
renderStyleguide | 4.570s
styleguideBundle | 2.163s
renderPages | 2.189s
componentTests | 3.723s

**Comment by kamsar** [comment]
> There is no way that I know of to run loaders only with specific entry file. we want .css files to be a null loader on scripts.jsx and .css files to be a extract text loader on styles.css

Does the `include` property do this?

Are all the webpack configs independent? Like, could we `spawn` multiple webpack processes to do them all at the same time? Since node is single threaded this could gain sigificant efficiencies it seems like. I'm already doing an analog to this in LP where I am spawning gulp on more than one gulpfile at a time for speed.

**Comment by kamsar** [comment]
I think it would also make sense to 'load test' FC - with more like a complete site's worth of components even if they're dupes.

**Comment by krambuhl** [comment]
`include` has to do with the source directory of the file you're including, not the file that's requiring.  We need something that says, "when the require comes from entry A, use loader A. if the require comes from entry B, use loader B."

**Comment by krambuhl** [comment]
We can run all the configs independently for building, but while watching, you'd lose out on webpack's shared watch cache if you separated them out.

**Comment by kamsar** [comment]
Closing in favour of watching #96
